# Â© PixelmonMod 2012-2025

# For assistance visit https://pixelmonmod.com/wiki/Config
essence-radius: 30
essence-per-knockout: 1.5
rare-pokemon-essence-modifier: 3.75
random-tick-essence-gain-chance: 0.5
generate-cosmetics-in-card-shop: true
max-trades-per-trader: 12
essence-to-fill-jar: 100
card-types:
    tcg:stage_two: tcg:gui/cards/icons/stage2.png
    tcg:stadium: tcg:gui/cards/icons/stadium.png
    tcg:cosmetic: tcg:gui/cards/icons/cosmetic.png
    tcg:basic: tcg:gui/cards/icons/basic.png
    tcg:stage_one: tcg:gui/cards/icons/stage1.png
    tcg:trainer: tcg:gui/cards/icons/trainer.png
saved-u-i-scale: -1
